### ISSUE TITLE
Prośba o dodanie możliwości pobierania wybranych kursów poprzez wskazanie ich numerów

### ISSUE THREAD

**Issue by grzech67** [nonab/strefakursow-downloader#1]
Cześć,

Na ten moment skrypt strefakursow-downloader umożliwia pobranie pojedynczego kursu poprzez podanie jego numeru lub wszystkich kursów naraz (poprzez wpisanie 0). Brakuje jednak możliwości wskazania kilku konkretnych kursów do pobrania w jednej sesji, np. poprzez podanie ich numerów w formacie listy (np. 3,4,5).

Taka funkcjonalność byłaby bardzo przydatna, szczególnie w sytuacjach, gdy użytkownik chce pobrać kilka kursów, ale nie wszystkie.

Czy byłaby możliwość dodania takiej opcji? Idealnie, gdyby skrypt obsługiwał listę numerów kursów oddzielonych przecinkami, a następnie iterował przez podane wartości i pobierał wybrane kursy.

**Comment by nonab** [comment]
dodane w wersji 7.0
